### ISSUE TITLE
TypeError: Cannot read property 'iconOn' of undefined

### ISSUE THREAD

**Issue by vishnureddy** [rajeshwarpatlolla/ionic-ratings#14]
Hi Rajesh,

I am trying to integrate the same which mentioned in Readme.md file. But I am unable to load stars on my broser. i am getting an error in console which is 

TypeError: Cannot read property 'iconOn' of undefined
    at link (http://localhost:8100/lib/ionic-rating.js:33:40)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17040:44
    at invokeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17046:9)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16556:11)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15905:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13) <div class="text-center ionic_ratings" ratingsobj="ratingsObject">

May i know the reason why i am getting this error

**Comment by pocholojm** [comment]
I have the same ploblem. Any solution?

**Comment by pocholojm** [comment]
A companion found a solution. This is:

```
$templateRequest([URLVIEW]).then(function(html){
        $timeout(function(){
         var template = angular.element(html);
         element.append(template);
         $compile(template)(scope);
        },500);
      });
```

You have to comment templateUrl or template in directive and inject $templateRequest and $compile.

**Comment by Vulkh88** [comment]
You just have to put the name of your controller in the ng-controller in the html where you are going to use the  ionic-rating 
`<ion-content ng-controller='RatingController'>
          <div ng-repeat='i in [1,2,3]'>
             <ionic-ratings ratingsobj='ratingsObject' index='$index'></ionic-ratings>
          </div>
        </ion-content>`

**Comment by gw00p** [comment]
Hi all,
i have got the same problem and i solved it.

For me the cause is that i have declared the 
> ratingsObject = {
>         iconOn : 'ion-ios-star',
>         iconOff : 'ion-ios-star-out
> ....

not directly in the $scope but inside another oject var declared in the $scope like:
$scope.vm.ratingsObject = {iconOn : 'ion-ios-star', .....}
I've just declared and set ratingObject in the $scope and everything went ok.

**Comment by aliayoubi** [comment]
i put it in first after code it work
